
#--- Page

h4cc_hhvm_progress_homepage:
    pattern:  /
    defaults: { _controller: h4ccHHVMProgressBundle:Page:index }

h4cc_hhvm_progress_script_download:
    pattern:  /scripts/hhvm_status.php
    defaults: { _controller: h4ccHHVMProgressBundle:Page:scriptDownload }

h4cc_hhvm_progress_about:
    pattern:  /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    h4ccHHVMProgressBundle:Page:about.html.twig

h4cc_hhvm_progress_help:
    pattern:  /help
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    h4ccHHVMProgressBundle:Page:help.html.twig


#--- Packages

h4cc_hhvm_progress_packages_supporting:
    pattern:  /tested-with-hhvm
    defaults: { _controller: h4ccHHVMProgressBundle:Package:listSupporting }

h4cc_hhvm_progress_packages_allowed_failure:
    pattern:  /partial-tested-hhvm
    defaults: { _controller: h4ccHHVMProgressBundle:Package:listAllowedFailure }

h4cc_hhvm_progress_packages_api_update:
    pattern:  /package/{name}/update.json
    defaults: { _controller: h4ccHHVMProgressBundle:Package:apiUpdatePackage }
    requirements:
        name: .+

h4cc_hhvm_progress_packages_api_get:
    pattern:  /package/{name}.json
    defaults: { _controller: h4ccHHVMProgressBundle:Package:apiGetPackage }
    requirements:
        name: .+

h4cc_hhvm_progress_packages_show:
    pattern:  /package/{name}
    defaults: { _controller: h4ccHHVMProgressBundle:Package:showPackage }
    requirements:
        name: .+

h4cc_hhvm_progress_packages_needing_help:
    pattern:  /needing-help
    defaults: { _controller: h4ccHHVMProgressBundle:Package:needingHelp }


#--- ComposerCheck

h4cc_hhvm_progress_composer_form:
    pattern:  /composer-lock-upload
    defaults: { _controller: h4ccHHVMProgressBundle:ComposerCheck:form }
    methods:  [GET]

h4cc_hhvm_progress_composer_check:
    pattern:  /composer-lock-upload
    defaults: { _controller: h4ccHHVMProgressBundle:ComposerCheck:check }
    methods:  [POST]

h4cc_hhvm_progress_composer_graph:
    pattern:  /composer-graph
    defaults: { _controller: h4ccHHVMProgressBundle:ComposerCheck:graph }


#--- Search

h4cc_hhvm_progress_search:
    pattern:  /search
    defaults: { _controller: h4ccHHVMProgressBundle:Search:result }


#--- Badges

h4cc_hhvm_progress_badges_json:
    pattern:  /badge/{name}.json
    defaults: { _controller: h4ccHHVMProgressBundle:Badges:json }
    requirements:
        name: .+

h4cc_hhvm_progress_badges_show:
    pattern:  /badge/{name}.{type}
    defaults: { _controller: h4ccHHVMProgressBundle:Badges:show }
    requirements:
        name: .+
        type: png|svg


#--- Graphs

h4cc_hhvm_progress_graphs_list:
    pattern:  /graphs/
    defaults: { _controller: h4ccHHVMProgressBundle:Graphs:list }


#--- Statistics

h4cc_hhvm_progress_statistics_index:
    pattern:  /statistics/
    defaults: { _controller: h4ccHHVMProgressBundle:Stats:index }

