imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    # Needing some special MySQL compatible functions.
                    datetime_functions:
                        date:         Luxifer\DQL\Datetime\Date
                        date_format:  Luxifer\DQL\Datetime\DateFormat
                        month:        Luxifer\DQL\Datetime\Month
                        year:         Luxifer\DQL\Datetime\Year

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

#lsw_memcache:
#    session:
#        client: default
#    clients:
#        default:
#            hosts:
#              - { dsn: localhost, port: 11211 }
#            options:
#                prefix_key: "hhvm_"

doctrine_cache:
    providers:
        cache:
            namespace: hhvm_
            memcached:
                servers:
                    127.0.0.1: 11211
            aliases:
                - memcache.default

